library:
  source-dirs: src
tests:
  spa-template-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spa-template
copyright: 2018 Jan Schulte
maintainer: jan@janschulte.com
ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
dependencies:
- mtl
- directory
- text-show
- text
- base >= 4.7 && < 5
- servant
- servant-server
- aeson
- wai
- warp
- time
default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
name: spa-template
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Jan Schulte
github: janschultecom/spa-template
license: Apache-2.0
executables:
  spa-template-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spa-template
description: Please see the README on GitHub at <https://github.com/janschultecom/spa-template#readme>
